# https://en.wikipedia.org/wiki/Italian_cuisine

type = "country"

[translation]
  [translation.en]
    term = "italy"
    adj = "italian"


[cuisine]
  [cuisine.pizza.translation]
    [cuisine.pizza.translation.en]
      term = "pizza"
