# https://en.wikipedia.org/wiki/Oceanic_cuisine
# https://en.wikipedia.org/wiki/Oceania
# https://en.wikipedia.org/wiki/Australasia

[translation]
  [translation.en]
    term = "australasia"
    adj = "australasian"
