[__info__]
  groups = "../translations/culinary-groups.toml"
  names = "../translations/culinary-names.toml"
  diets = "../translations/diet-names.toml"

[meat]
  [meat.__info__]
    exclude-diet = ["vegan", "vegetarian", "pescetarian", "raw-vegan", "fruitarian"]
  [meat.pork]
    [meat.pork.__info__]
      exclude-diet = ["kosher", "halal"]

[vegetable]
  [vegetable.__info__]
    exclude-diet = ["carnivorous", "ketogenic"]
  [vegetable.spring-onion]
  [vegetable.tuber]
    [vegetable.tuber.__info__]
      exclude-diet = ["fruitarian"]
    [vegetable.tuber.potato]
